// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spbytlvfszjnnewevxkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwYnl0bHZmc3pqbm5ld2V2eGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzg5ODksImV4cCI6MjA2MzY1NDk4OX0.jXgOlyjdiRQcB6UqhW0ev-_zsFPl818v1GYCnzz_Fy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);